version: '3'

networks:
  beam-network:
    driver: bridge

services:

## Messaging & Streaming

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - beam-network      
      
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - beam-network

## Storage & DB  
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/minio:/data      
    environment:
      MINIO_ACCESS_KEY: "$MINIO_ROOT_USER"
      MINIO_SECRET_KEY: "$MINIO_ROOT_PASSWORD"
    command: server /data --console-address ":9001"
    networks:
      - beam-network      

  trino:
    image: trinodb/trino:411
    hostname: trino
    ports:
      - "8080:8080"
    volumes:
      - ./conf/trino/catalog:/etc/trino/catalog
    depends_on: 
      - minio
      - metastore
    networks:
      - beam-network        
  
  metastore:
    image: 'bitsondatadev/hive-metastore:latest'
    hostname: metastore
    ports:
      - '9083:9083'
    volumes:
      - ./conf/metastore/metastore-site.xml:/opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml:ro
    environment:
      METASTORE_DB_HOSTNAME: mariadb
    depends_on:
      - mariadb
    networks:
      - beam-network

  mariadb:
    image: 'mariadb:10.8.2'
    hostname: mariadb
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    networks:
      - beam-network

  # trino-bootstrap3:
  #   build: ./cli
  #   restart: "no" #runs once
  #   networks:
  #     - beam-network
  #   depends_on:
  #     - trino

## UI
  metabase:
    image: metabase/metabase:v0.45.3
    ports:
      - "3000:3000"
    networks:
      - beam-network
    volumes:
      - ./conf/metabase/plugins:/plugins
      - ./conf/metabase/data:/metabase-data
    environment:
      MB_PLUGINS_DIR: /plugins
      MB_DB_FILE: /metabase-data/metabase.db
    depends_on:
      - trino

  minio-console:
    image: minio/console:v0.26.3
    ports:
      - "9090:9090"
    networks:
      - beam-network
    command: server
    environment:
      CONSOLE_MINIO_SERVER: http://minio:9000
    depends_on:
      - minio

## BEAM

  flink-master:
    image: bde2020/flink-master:1.14.5-hadoop3.2
    hostname: flink-master
    container_name: flink-master
    networks:
      - beam-network
    ports:
      - "8082:8080"
      - "8083:8081" #UI

  flink-worker:
    image: bde2020/flink-worker:1.14.5-hadoop3.2
    hostname: flink-worker
    container_name: flink-worker
    networks:
      - beam-network
    environment:
      - FLINK_MASTER_PORT_6123_TCP_ADDR=flink-master
      - FLINK_NUM_TASK_SLOTS=10
    depends_on:
        - flink-master    

volumes:
  trino:
    name: trino
    driver: local  
  metastore_conf:
    driver: local
  minio-data:
    driver: local
  metabase:
    driver: local 
  cli:
    driver: local  